### PR TITLE
Added option to use Auto mode without Plasma enabled

### PR DESCRIPTION
**Pull request by sandervalstar**
Hi Indu,
Thank you so much for creating this custom component! I made a small change as I like running the purifier in auto mode without PlasmaWave enabled. Would really appreciate it if you could take a look to see if you agree with my changes and if this would be ok to merge.

Thank you!
Sander

### CODE REVIEW

**Comment by iprak** [comment]
I definitely see such a need but the plasma mode gets enabled at Winix server end when `auto` is selected. Forcing it to be disabled for auto also does not match the usage from mobile app so I am not in favor of this change. 

It sounds weird but if the new option could be AUTO_NO_PLASMA then it will be consistent with mobile app.

**Comment by sandervalstar** [comment]
I see, that makes sense. Should we then change it to AUTO_NO_PLASMA and MANUAL_NO_PLASMA to keep the naming of those two options consistent? Or alternatively maybe have a separate button for plasma like the Winix app?

**Comment by iprak** [comment]
I don't think the Entity card can support custom options unless we modify it which would have to be in HA code base. 
Some folks use this [Purifier custom card](https://github.com/denysdovhan/purifier-card) which can be customized via service.


As far as your changes go. We can break compatibility with the Winix app and keep Plasma off for "Auto". If anyone was using "Auto" then they can switch to use "Auto+Plasma". I have 2 purifiers around cat litter boxes on a timer and I think Plasma helps :-)

**Comment by sandervalstar** [comment]
Ok, and how about changing it to AUTO_NO_PLASMA and MANUAL_NO_PLASMA? That would resolve the behavior difference with the Winix app right? I don't think in the Winix app choosing manual will use no plasma by default. It'll just keep plasma on if it was already on and keep it off if it was already off as far as I could tell.

**Comment by iprak** [comment]
There is no manual mode in the app, just picking a speed puts it in manual mode. I am okay going with AUTO_NO_PLASMA and MANUAL_NO_PLASMA. What are you going to name the preset modes?

**Comment by sandervalstar** [comment]
Something like this?
```python
PRESET_MODE_AUTO = "Auto"
PRESET_MODE_AUTO_NO_PLASMA = "Auto (no Plasma)"
PRESET_MODE_MANUAL = "Manual"
PRESET_MODE_MANUAL_NO_PLASMA = "Manual (no Plasma)"
PRESET_MODE_SLEEP = "Sleep"
```

**Comment by iprak** [comment]
So the preset mode can be set using the service `fan.set_preset_mode`. I did not find display name for presets so one would have to exactly pass  "Manual (no Plasma)"  for now which is why I was asking about the names. But I can look into providing numeric values separately.

**Comment by sandervalstar** [comment]
Ok, I made the change in my repo.

```python
PRESET_MODE_AUTO = "Auto"
PRESET_MODE_AUTO_PLASMA_OFF = "Auto (PlasmaWave off)"
PRESET_MODE_MANUAL = "Manual"
PRESET_MODE_MANUAL_PLASMA_OFF = "Manual (PlasmaWave off)"
PRESET_MODE_SLEEP = "Sleep"
```

Not sure what you mean with needing to use `fan.set_preset_mode` and numeric values. I have it working now without having to do that unless I'm missing something.

**Comment by iprak** [comment]
Changes look good, can you update the readme to call out the new preset modes?

**Comment by sandervalstar** [comment]
Ok, I just updated the screenshot. 

By the way I did notice that when I turn the purifier off and back on again, it will always use revert back to using auto mode. This does seem to be the same as the behavior of the purifier itself, but it is a bit weird that it doesn't remember my last selection. This is a separate issue though.

**Comment by iprak** [comment]
Thank you.

**Pull request merged**
